Resources:
  GatewayResponseInvalidApiKey:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      RestApiId:
        Ref: 'ApiGatewayRestApi'
      ResponseType: INVALID_API_KEY
      ResponseTemplates:
        application/json: "{\"error\": \"unauthorized\"}"
      StatusCode: '401'
