name: CI

on: [pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Serverless credentials
      run: |
        mkdir ~/.aws && echo "${{ secrets.AWS_LAMBDA_PROFILES }}" > ~/.aws/credentials
    - name: Install Dependencies
      run: npm i
    - name: Linter
      run: npm run lint
    - name: Unit tests
      run: npm test
